/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.4-dev at Thu Sep 26 18:56:18 2013. */

#include "messages.pb.h"



const pb_field_t Info_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC, FIRST, Info, version, version, 0),
    PB_LAST_FIELD
};

const pb_field_t sensors_t_fields[6] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC, FIRST, sensors_t, rpm, rpm, 0),
    PB_FIELD2(  2, UINT32  , REQUIRED, STATIC, OTHER, sensors_t, speed, rpm, 0),
    PB_FIELD2(  3, UINT32  , REQUIRED, STATIC, OTHER, sensors_t, strain_gauge, speed, 0),
    PB_FIELD2(  4, UINT32  , REQUIRED, STATIC, OTHER, sensors_t, tc_switch, strain_gauge, 0),
    PB_FIELD2(  5, UINT32  , REQUIRED, STATIC, OTHER, sensors_t, vbat, tc_switch, 0),
    PB_LAST_FIELD
};

const pb_field_t Settings_data_fields[12] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC, FIRST, Settings_data, functions, functions, 0),
    PB_FIELD2(  2, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, cut_type, functions, 0),
    PB_FIELD2(  3, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, sensor_threshold, cut_type, 0),
    PB_FIELD2(  4, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, slip_threshold, sensor_threshold, 0),
    PB_FIELD2(  5, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, sensor_gain, slip_threshold, 0),
    PB_FIELD2(  6, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, sensor_direction, sensor_gain, 0),
    PB_FIELD2(  7, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, min_speed, sensor_direction, 0),
    PB_FIELD2(  8, UINT32  , REQUIRED, STATIC, OTHER, Settings_data, min_rpm, min_speed, 0),
    PB_FIELD2(  9, BYTES   , REQUIRED, STATIC, OTHER, Settings_data, gears_ratio, min_rpm, 0),
    PB_FIELD2( 10, BYTES   , REQUIRED, STATIC, OTHER, Settings_data, gears_cut_time, gears_ratio, 0),
    PB_FIELD2( 11, BYTES   , REQUIRED, STATIC, OTHER, Settings_data, tc_gear_trim, gears_cut_time, 0),
    PB_LAST_FIELD
};

const pb_field_t settings_t_fields[3] = {
    PB_FIELD2(  1, MESSAGE , REQUIRED, STATIC, FIRST, settings_t, data, data, &Settings_data_fields),
    PB_FIELD2(  2, UINT32  , REQUIRED, STATIC, OTHER, settings_t, CRCValue, data, 0),
    PB_LAST_FIELD
};

const pb_field_t status_t_fields[5] = {
    PB_FIELD2(  1, BOOL    , REQUIRED, STATIC, FIRST, status_t, shifting, shifting, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC, OTHER, status_t, slipping, shifting, 0),
    PB_FIELD2(  3, UINT32  , REQUIRED, STATIC, OTHER, status_t, slipping_pct, slipping, 0),
    PB_FIELD2(  4, UINT32  , REQUIRED, STATIC, OTHER, status_t, acceleration, slipping_pct, 0),
    PB_LAST_FIELD
};

const pb_field_t light_settings_t_fields[3] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC, FIRST, light_settings_t, state, state, 0),
    PB_FIELD2(  2, UINT32  , REQUIRED, STATIC, OTHER, light_settings_t, duration, state, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(settings_t, data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Info_sensors_t_Settings_data_settings_t_status_t_light_settings_t)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(settings_t, data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Info_sensors_t_Settings_data_settings_t_status_t_light_settings_t)
#endif

