/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.4-dev at Thu Sep 26 16:29:49 2013. */

#include "sensors.pb.h"



const pb_field_t Sensors_fields[2] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC, FIRST, Sensors, lucky_number, lucky_number, 0),
    PB_LAST_FIELD
};


