/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.4-dev at Thu Sep 26 16:29:49 2013. */

#ifndef _PB_STATUS_PB_H_
#define _PB_STATUS_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _Status {
    int32_t lucky_number;
} Status;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Status_lucky_number_tag                  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Status_fields[2];

/* Maximum encoded size of messages (where known) */
#define Status_size                              6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
